# Generated by Django 5.0.6 on 2024-08-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('star', models.IntegerField()),
                ('review', models.TextField()),
                ('empathy', models.FloatField()),
                ('title2', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('label', models.IntegerField()),
            ],
        ),
    ]
